### PR TITLE
Docker multi-arch support

### PR DESCRIPTION
**Pull request by joseluisq**

### CODE REVIEW

**Comment by joseluisq** [comment]
The `linux/arm64` CI workflow exceeded the [GitHub Actions 6 hours of execution time limit](https://docs.github.com/en/actions/learn-github-actions/usage-limits-billing-and-administration#usage-limits) because of the qemu emulation.

So it will be temporarily disabled until https://github.com/actions/runner-images/issues/5631

**Comment by joseluisq** [comment]
However, I could use temporarily a local `arm64` machine to build and push the multi-arch images.

**Comment by markmandel** [comment]
As you are probably aware, if you built it on a separate machine, you'll need to run a separate `docker manifest` (https://docs.docker.com/engine/reference/commandline/manifest/) set of commands to build a new multi-platform tag, so you may want to put the arch type on the image tag, and then do a separate manifest for the main tag.

**Comment by markmandel** [comment]
Apparently it is on the roadmap: https://github.com/github/roadmap/issues/528

**Comment by joseluisq** [comment]
> As you are probably aware, if you built it on a separate machine, you'll need to run a separate `docker manifest` (https://docs.docker.com/engine/reference/commandline/manifest/) set of commands to build a new multi-platform tag, so you may want to put the arch type on the image tag, and then do a separate manifest for the main tag.

@markmandel Thanks for pointed that out! Yes I will do that as a workaround when the next Rust release comes in.

**Comment by joseluisq** [comment]
**Update:** Turns out that I don't have the arm64 machine anymore. **But** there is a possibility to perform Linux arm64 builds via Cirrus CI https://github.com/cirruslabs/cirrus-ci-docs/pull/905/ which is awesome! I didn't know until now.
https://cirrus-ci.org/guide/linux/ 

So I could add Cirrus CI integration to perform the Docker multi-arch update for `linux/arm64`. I will investigate a bit more. Even I'm considering the option of moving out to Cirrus CI. :sweat_smile:

**Comment by joseluisq** [comment]
**Update:** I already did some experiments with Cirrus this week but I got a small inconvenience when building [an image](https://github.com/joseluisq/docker-hello-native) on the `arm64` instance there. So I _hope_ I can get this problem sorted out in some way. Otherwise, I will try to look for alternatives.
https://github.com/cirruslabs/cirrus-ci-docs/issues/1034#issuecomment-1295656040

**Comment by joseluisq** [comment]
Full Docker multi-arch support via Cirrus CI using two (amd64/arm64) separate native containers is ready to work (see #19).
And since [Rust 1.65.0 ](https://blog.rust-lang.org/2022/11/03/Rust-1.65.0.html) is now out then a new equivalent release should come in the next hours :muscle:

**Pull request merged**
